packages:
  - 'packages/*'
  - 'packages/near-api-ts/universal/tests/utils/transactionIndexer'
  - 'playgrounds/react-near-ts/*'
allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@near-js/jsonrpc-types@1.7.3'
